Repository jekyll/jekyll-import, pull requests merged in 2021-04, with the labels that each got.

#413 Add support for Podcast RSS feed imports
  lib/jekyll-import/importers/rss.rb
Labels: feature

#390 Add private helpers to simplify Blogger importer
  lib/jekyll-import/importers/blogger.rb
Labels: internal, refactor

#419 Change data[author] to a string scalar
  lib/jekyll-import/importers/s9y_database.rb
Labels: fix

#388 Refactor Blogger importer with guard clauses
  lib/jekyll-import/importers/blogger.rb
Labels: internal, refactor
